language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-spdy/.travis_build_config.rb build_config.rb
script: 
  - rake all test
notifications:
  webhooks:
    - secure: "ExZCB3NeEOr7JDjxv4GYmgMa4ogrmlKzCgXYzmUbHQIV65HBJDRZNsRPOXkRNqQbaCkswTzqY1smLmgI/1/uLO/wgnjoDtEPXJe8m+GEI6G0NcxW6b5KkP4vBFhfROh84bKcOaLayEc4FsbB/XRi+fjxgHFkwP58Qzaf9rSAqEY="

